# Dockerfile.ubuntu
FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y openssh-server sudo python3 python3-pip && \
    mkdir /run/sshd

RUN useradd -m ansible -s /bin/bash && \
    echo 'ansible:password' | chpasswd && \
    echo 'ansible ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
